### PR TITLE
Passwordless SOGo auth: support for calendar invitations and calender/contacts subscriptions

### LINKED ISSUE #4333: Unable to invite attendees to SOGo calendar event when authenticated via Mailcow
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

When inviting an attendee to a SOGo calendar event, having authenticated via the Mailcow web interface, the event dialog closes and the page refreshes. No event is created. The problem does not occur when authenticating directly via the SOGo login dialog.

Mailcow installed fresh today. Tested on an SSD Nodes 8GB/2 core VPS under both Debian 10 and Ubuntu 20.04. Also tested on a Hyper-V virtual machine.

## Logs

```
acme-mailcow_1       | OK
clamd-mailcow_1      | Wed Nov 24 10:58:38 2021 -> Activating the newly loaded database...
dockerapi-mailcow_1  | 172.22.1.9 - - [24/Nov/2021 10:50:30] "POST /containers/61b4d9619c9c7051a9a1c1cd839704bd3823c49afcfc1d3383ffa893fc0f4d1b/restart HTTP/1.1" 200 -
dovecot-mailcow_1    | Nov 24 11:25:43 7c8a192442d4 dovecot: imap-login: Disconnected: Aborted login by logging out (no auth attempts in 0 secs): user=<>, rip=172.22.1.5, lip=172.22.1.250
mysql-mailcow_1      | Version: '10.5.13-MariaDB-1:10.5.13+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
netfilter-mailcow_1  | Watching Redis channel F2B_CHANNEL
nginx-mailcow_1      | 172.22.1.5 - - [24/Nov/2021:11:25:59 -0700] "GET / HTTP/1.1" 200 15 "-" "check_http/v (nagios-plugins 2.3.2)"
ofelia-mailcow_1     | 2021-11-24T18:25:59.558Z  common.go:125 ▶ NOTICE [Job "sogo_sessions" (045cbf4902d7)] Finished in "545.78414ms", failed: false, skipped: false, error: none
olefy-mailcow_1      | olefy INFO <module> serving on ('0.0.0.0', 10055)
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::d -  24/Nov/2021:11:25:44 -0700 "HEAD /settings.php" 304
postfix-mailcow_1    | Nov 24 10:52:35 0cd4836ea8ad postfix/qmgr[349]: C68191621E2: removed
redis-mailcow_1      | 1:M 24 Nov 2021 11:21:54.113 * Background saving terminated with success
rspamd-mailcow_1     | 2021-11-24 11:25:11 #38(controller) <046d3b>; csession; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 0 regexps matched, 3174 regexps total, 2404 regexps cached, 0B scanned using pcre, 102B scanned total
sogo-mailcow_1       | Nov 24 11:25:59 61b4d9619c9c sogod [64]: mailcowdockerized_watchdog-mailcow_1.mailcowdockerized_mailcow-network "GET /SOGo.index/ HTTP/1.1" 200 2573/0 0.010 - - 0 - 13
solr-mailcow_1       | 2021-11-24 17:52:51.163 INFO  (commitScheduler-13-thread-1) [   ] o.a.s.u.DirectUpdateHandler2 end_commit_flush
unbound-mailcow_1    | [1637776017] unbound[1:0] info: generate keytag query _ta-4f66. NULL IN
watchdog-mailcow_1   | Wed Nov 24 11:26:15 MST 2021 Clamd health level: 100% (15/15), health trend: 0
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::d -  24/Nov/2021:11:26:20 -0700 "GET /sogo-auth.php" 200
nginx-mailcow_1      | 127.0.0.1 - - [24/Nov/2021:11:26:20 -0700] "GET /sogo-auth HTTP/1.0" 200 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:20 -0700] "GET /SOGo/so/jim@[my domain]/Calendar/personal/newguid HTTP/2.0" 200 55 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
sogo-mailcow_1       | Nov 24 11:26:20 61b4d9619c9c sogod [64]: 192.168.111.12 "GET /SOGo/so/jim@[my domain]/Calendar/personal/newguid HTTP/1.0" 200 55/0 0.003 - - 0 - 13
watchdog-mailcow_1   | Wed Nov 24 11:26:21 MST 2021 PHP-FPM health level: 100% (5/5), health trend: 0
rspamd-mailcow_1     | 2021-11-24 11:26:22 #38(controller) <e8eb02>; csession; rspamd_redis_connected: skip obtaining bayes tokens for BAYES_HAM of classifier bayes: not enough learns 2; 5 required
rspamd-mailcow_1     | 2021-11-24 11:26:22 #38(controller) <e8eb02>; csession; rspamd_redis_connected: skip obtaining bayes tokens for BAYES_SPAM of classifier bayes: not enough learns 0; 5 required
rspamd-mailcow_1     | 2021-11-24 11:26:22 #38(controller) <e8eb02>; csession; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 0 regexps matched, 3174 regexps total, 2404 regexps cached, 0B scanned using pcre, 102B scanned total
watchdog-mailcow_1   | Wed Nov 24 11:26:22 MST 2021 Rspamd health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Wed Nov 24 11:26:24 MST 2021 ACME health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Wed Nov 24 11:26:24 MST 2021 Postfix health level: 100% (8/8), health trend: 0
php-fpm-mailcow_1    | 172.22.1.10 -  24/Nov/2021:11:26:24 -0700 "GET /sogo-auth.php" 200
nginx-mailcow_1      | 127.0.0.1 - - [24/Nov/2021:11:26:24 -0700] "GET /sogo-auth HTTP/1.0" 200 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
sogo-mailcow_1       | Nov 24 11:26:24 61b4d9619c9c 2021-11-24 11:26:24.743 sogod[64:64] sortedFolders = ("<0x55923ac31ad0[SOGoContactSourceFolder]: name=[my domain] container=0x55923ac15ff0/Contacts>", "<0x55923a9f0c70[SOGoContactGCSFolder]: name=personal container=0x55923ac15ff0/Contacts ocs=/Users/jim@[my domain]/Contacts/personal>")
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:24 -0700] "GET /SOGo/so/jim@[my domain]/Contacts/allContactSearch?search=am HTTP/2.0" 200 205 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
sogo-mailcow_1       | Nov 24 11:26:24 61b4d9619c9c sogod [64]: 192.168.111.12 "GET /SOGo/so/jim@[my domain]/Contacts/allContactSearch?search=am HTTP/1.0" 200 449/0 0.008 - - 0 - 13
nginx-mailcow_1      | 127.0.0.1 - - [24/Nov/2021:11:26:24 -0700] "GET /sogo-auth HTTP/1.0" 200 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::d -  24/Nov/2021:11:26:24 -0700 "GET /sogo-auth.php" 200
sogo-mailcow_1       | Nov 24 11:26:24 61b4d9619c9c 2021-11-24 11:26:24.931 sogod[64:64] sortedFolders = ("<0x55923ab4d0e0[SOGoContactSourceFolder]: name=[my domain] container=0x55923ab77af0/Contacts>", "<0x55923ac95670[SOGoContactGCSFolder]: name=personal container=0x55923ab77af0/Contacts ocs=/Users/jim@[my domain]/Contacts/personal>")
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:24 -0700] "GET /SOGo/so/jim@[my domain]/Contacts/allContactSearch?search=amb HTTP/2.0" 200 205 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
sogo-mailcow_1       | Nov 24 11:26:24 61b4d9619c9c sogod [64]: 192.168.111.12 "GET /SOGo/so/jim@[my domain]/Contacts/allContactSearch?search=amb HTTP/1.0" 200 450/0 0.007 - - 0 - 13
sogo-mailcow_1       | Nov 24 11:26:26 61b4d9619c9c 2021-11-24 11:26:26.076 sogod[64:64] sortedFolders = ("<0x55923abe4310[SOGoContactSourceFolder]: name=[my domain] container=0x55923adcae90/Contacts>", "<0x55923ac5d9d0[SOGoContactGCSFolder]: name=personal container=0x55923adcae90/Contacts ocs=/Users/jim@[my domain]/Contacts/personal>")
php-fpm-mailcow_1    | 172.22.1.10 -  24/Nov/2021:11:26:26 -0700 "GET /sogo-auth.php" 200
nginx-mailcow_1      | 127.0.0.1 - - [24/Nov/2021:11:26:26 -0700] "GET /sogo-auth HTTP/1.0" 200 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:26 -0700] "GET /SOGo/so/jim@[my domain]/Contacts/allContactSearch?search=amb HTTP/2.0" 200 205 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
sogo-mailcow_1       | Nov 24 11:26:26 61b4d9619c9c sogod [64]: 192.168.111.12 "GET /SOGo/so/jim@[my domain]/Contacts/allContactSearch?search=amb HTTP/1.0" 200 450/0 0.006 - - 0 - 13
nginx-mailcow_1      | 127.0.0.1 - - [24/Nov/2021:11:26:26 -0700] "GET /sogo-auth HTTP/1.0" 200 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
nginx-mailcow_1      | 127.0.0.1 - - [24/Nov/2021:11:26:26 -0700] "GET /sogo-auth HTTP/1.0" 200 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::d -  24/Nov/2021:11:26:26 -0700 "GET /sogo-auth.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  24/Nov/2021:11:26:26 -0700 "GET /sogo-auth.php" 200
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:26 -0700] "GET /SOGo/so/jim@[my domain]/freebusy.ifb/ajaxRead?eday=20211130&sday=20211117 HTTP/2.0" 200 2 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
sogo-mailcow_1       | Nov 24 11:26:26 61b4d9619c9c sogod [66]: 192.168.111.12 "GET /SOGo/so/jim@[my domain]/freebusy.ifb/ajaxRead?eday=20211130&sday=20211117 HTTP/1.0" 200 2/0 0.005 - - 0 - 13
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:26 -0700] "GET /SOGo/so/amber@[my domain]/freebusy.ifb/ajaxRead?eday=20211130&sday=20211117 HTTP/2.0" 200 8281 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
sogo-mailcow_1       | Nov 24 11:26:26 61b4d9619c9c sogod [64]: 192.168.111.12 "GET /SOGo/so/amber@[my domain]/freebusy.ifb/ajaxRead?eday=20211130&sday=20211117 HTTP/1.0" 200 8281/0 0.012 32698 74% 0 - 13
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::d -  24/Nov/2021:11:26:26 -0700 "GET /sogo-auth.php" 200
nginx-mailcow_1      | 127.0.0.1 - - [24/Nov/2021:11:26:26 -0700] "GET /sogo-auth HTTP/1.0" 200 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:26 -0700] "GET /SOGo/so/jim@[my domain]/Calendar/ HTTP/2.0" 302 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
sogo-mailcow_1       | Nov 24 11:26:26 61b4d9619c9c sogod [64]: 192.168.111.12 "GET /SOGo/so/jim@[my domain]/Calendar/ HTTP/1.0" 302 0/0 0.004 - - 0 - 13
php-fpm-mailcow_1    | 172.22.1.10 -  24/Nov/2021:11:26:26 -0700 "GET /sogo-auth.php" 200
nginx-mailcow_1      | 127.0.0.1 - - [24/Nov/2021:11:26:26 -0700] "GET /sogo-auth HTTP/1.0" 200 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:26 -0700] "GET /SOGo/so/jim@[my domain]/Calendar/view HTTP/2.0" 200 19059 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
sogo-mailcow_1       | Nov 24 11:26:26 61b4d9619c9c sogod [64]: 192.168.111.12 "GET /SOGo/so/jim@[my domain]/Calendar/view HTTP/1.0" 200 19059/0 0.035 78995 75% 260K - 13
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:26 -0700] "GET /SOGo.woa/WebServerResources/js/theme.js?lm=1637775794 HTTP/2.0" 304 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:26 -0700] "GET /SOGo.woa/WebServerResources/js/custom-sogo.js?lm=1637775794 HTTP/2.0" 304 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:27 -0700] "GET /SOGo.woa/WebServerResources/img/sogo.ico?lm=1637775794 HTTP/2.0" 200 4915 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
nginx-mailcow_1      | 127.0.0.1 - - [24/Nov/2021:11:26:27 -0700] "GET /sogo-auth HTTP/1.0" 200 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
nginx-mailcow_1      | 127.0.0.1 - - [24/Nov/2021:11:26:27 -0700] "GET /sogo-auth HTTP/1.0" 200 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::d -  24/Nov/2021:11:26:27 -0700 "GET /sogo-auth.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  24/Nov/2021:11:26:27 -0700 "GET /sogo-auth.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::d -  24/Nov/2021:11:26:27 -0700 "GET /sogo-auth.php" 200
nginx-mailcow_1      | 127.0.0.1 - - [24/Nov/2021:11:26:27 -0700] "GET /sogo-auth HTTP/1.0" 200 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:27 -0700] "GET /SOGo/so/jim@[my domain]/Calendar/eventsblocks?ed=20211128&sd=20211122&view=weekview HTTP/2.0" 200 322 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
sogo-mailcow_1       | Nov 24 11:26:27 61b4d9619c9c sogod [63]: 192.168.111.12 "GET /SOGo/so/jim@[my domain]/Calendar/eventsblocks?ed=20211128&sd=20211122&view=weekview HTTP/1.0" 200 744/0 0.020 - - 0 - 13
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:27 -0700] "GET /SOGo/so/jim@[my domain]/Calendar/alarmslist?browserTime=1637778386 HTTP/2.0" 200 63 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
sogo-mailcow_1       | Nov 24 11:26:27 61b4d9619c9c sogod [64]: 192.168.111.12 "GET /SOGo/so/jim@[my domain]/Calendar/alarmslist?browserTime=1637778386 HTTP/1.0" 200 63/0 0.029 - - 0 - 13
php-fpm-mailcow_1    | 172.22.1.10 -  24/Nov/2021:11:26:27 -0700 "GET /sogo-auth.php" 200
nginx-mailcow_1      | 127.0.0.1 - - [24/Nov/2021:11:26:27 -0700] "GET /sogo-auth HTTP/1.0" 200 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:27 -0700] "GET /SOGo/so/jim@[my domain]/Calendar/weekview?day=20211124 HTTP/2.0" 200 3571 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
sogo-mailcow_1       | Nov 24 11:26:27 61b4d9619c9c sogod [64]: 192.168.111.12 "GET /SOGo/so/jim@[my domain]/Calendar/weekview?day=20211124 HTTP/1.0" 200 3571/0 0.018 74972 95% 0 - 13
dovecot-mailcow_1    | Nov 24 11:26:27 7c8a192442d4 dovecot: imap-login: Login: user=<jim@[my domain]>, method=PLAIN, rip=172.22.1.248, lip=172.22.1.250, mpid=1887
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::d -  24/Nov/2021:11:26:27 -0700 "GET /sogo-auth.php" 200
php-fpm-mailcow_1    | 172.22.1.10 -  24/Nov/2021:11:26:27 -0700 "GET /sogo-auth.php" 200
nginx-mailcow_1      | 127.0.0.1 - - [24/Nov/2021:11:26:27 -0700] "GET /sogo-auth HTTP/1.0" 200 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
nginx-mailcow_1      | 127.0.0.1 - - [24/Nov/2021:11:26:27 -0700] "GET /sogo-auth HTTP/1.0" 200 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:27 -0700] "POST /SOGo/so/jim@[my domain]/Mail/0/folderINBOX/changes HTTP/2.0" 200 20 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
sogo-mailcow_1       | Nov 24 11:26:27 61b4d9619c9c sogod [66]: 192.168.111.12 "POST /SOGo/so/jim@[my domain]/Mail/0/folderINBOX/changes HTTP/1.0" 200 20/126 0.199 - - 0 - 14
dovecot-mailcow_1    | Nov 24 11:26:27 7c8a192442d4 dovecot: imap(jim@[my domain])<1887><zGX9/ozRUNusFgH4>: Disconnected: Logged out in=111 out=1618 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:27 -0700] "POST /SOGo/so/jim@[my domain]/Calendar/saveSelectedList HTTP/2.0" 204 0 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
sogo-mailcow_1       | Nov 24 11:26:27 61b4d9619c9c sogod [63]: 192.168.111.12 "POST /SOGo/so/jim@[my domain]/Calendar/saveSelectedList HTTP/1.0" 204 0/25 0.014 - - 0 - 13
nginx-mailcow_1      | 192.168.111.12 - - [24/Nov/2021:11:26:27 -0700] "GET /SOGo/so/jim@[my domain]/Calendar/eventslist?asc=1&day=20211124&filterpopup=view_next7&search=title_Category_Location&sort=start&value= HTTP/2.0" 200 243 "https://mailcow.[my domain]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
sogo-mailcow_1       | Nov 24 11:26:27 61b4d9619c9c sogod [64]: 192.168.111.12 "GET /SOGo/so/jim@[my domain]/Calendar/eventslist?asc=1&day=20211124&filterpopup=view_next7&search=title_Category_Location&sort=start&value= HTTP/1.0" 200 452/0 0.012 - - 0 - 13
nginx-mailcow_1      | 172.22.1.5 - - [24/Nov/2021:11:26:29 -0700] "GET / HTTP/1.1" 200 15 "-" "check_http/v (nagios-plugins 2.3.2)"
watchdog-mailcow_1   | Wed Nov 24 11:26:29 MST 2021 Nginx health level: 100% (5/5), health trend: 0
```

## Reproduction

On a fresh Mailcow installation on a fresh Debian or Ubuntu install:

- Log in to Mailcow web interface as admin.
- Create a domain.
- Create two mailboxes.
- Log out of Mailcow web interface.
- Log in to Mailcow web interface as one of the mailbox users created above.
- Click "Login to webmail"
- Wait until you have received notification messages that Personal Address Book and Personal Calendar have been created.
- Create a new calendar event.
- In the Invite Attendees field, enter/select the other mailbox user created above.
- Event creation dialog closes and page refreshes. Event is not saved.

## System information

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | I believe SSD Nodes uses KVM |
| Server/VM specifications (Memory, CPU Cores) | 8GB, 2 cores |
| Docker Version (`docker version`) | 20.10.11 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2 |
| Reverse proxy (custom solution) | None |

- Output of `git diff origin/master` (certs and keys are no longer in use):
```
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -198,3 +198,6 @@ parent_domain_matches_subdomains = debug_peer_list,fast_flush_domains,mynetworks

 # DO NOT EDIT ANYTHING BELOW #
 # User overrides #
+
+myhostname = mailcow.grusendorf.lan
+
```
- No firewall installed

- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254`:
151.101.193.69
151.101.1.69
151.101.129.69
151.101.65.69

### PR DESCRIPTION
**Pull request by mkuron**
Inviting someone to a calendar event triggers a request to `/SOGo/so/otheruser@example.com/freebusy.ifb/ajaxRead`. Attempting to subscribe to someone's calendar/contacts triggers a request to `/SOGo/so/otheruser@example.com/foldersSearch`. The email address in the URL is different from the logged-in user, which needs to be handled appropriately by sogo-auth.php.

Fixes #4333.

@keenmouse, could you please try this patch on your server and confirm that it fixes the issue for you too? @jkellerer, since you worked on the app passwords that use this authentication mechanism, could you please have a quick look at my patch? Also @mhofer117, who did the original work on passwordless SOGo authentication.

@DerLinkman, if you are okay with that, I would like to merge this straight to master instead of going through staging. It's a bugfix, and it's relatively simple, so I would like to get this to users as soon as possible.

### CODE REVIEW

**Comment by DerLinkman** [comment]
@mkuron I actually have to more hotfixes for the JanMooary Update. @FreddleSpl0it you have a bug fix for WebAuthn if i´m right + the Versioning for the WebUI. 

So we basically have 4 Fixes + Additions for 2022-01a <-- Release Tag.

**Comment by mkuron** [comment]
Okay, then let's release these all together. I'd like to get @keenmouse to test it before we merge, and if possible @jkellerer to comment because he probably understands the sogo-auth.php mechanism better than me.

**Comment by DerLinkman** [comment]
So i would like to merge it into staging as i will release the new hotfix release (2022-01a) as soon as the tests are done :)

**Comment by keenmouse** [comment]
> @keenmouse, could you please try this patch on your server and confirm that it fixes the issue for you too?

Lol… I'm going to need some hand-holding in order to do so. I'm not a developer or git wizard and have no idea how to apply a patch.

Thanks.

**Comment by dragoangel** [comment]
I will test it tomorrow

**Comment by keenmouse** [comment]
Just pasted the new lines in sogo-auth.php and tested, and it works! Thanks so much.

File: data/web/sogo-auth.php [hunk 1]
```diff
@@ -89,6 +89,13 @@
     header("X-Auth: Basic ".base64_encode("$username:$password"));
     header("X-Auth-Type: Basic");
     exit;
+  } elseif(isset($_SESSION['mailcow_cc_username'])) {
```
Comment (mhofer117) [inline data/web/sogo-auth.php]: As far as I know, mailcow_cc_username will not be a valid email if the user is admin / domain admin.
So the current proposal would essentially send invalid basic_auth credentials to SOGo in some cases / not work for the ADMIN_EMAIL_LOGIN feature.

Maybe the following would be more concise:
```
} elseif (
      is_array($_SESSION[$session_var_user_allowed]) &&
      count($_SESSION[$session_var_user_allowed]) === 1
) {
    $username = $_SESSION[$session_var_user_allowed][0];
```

This would prevent sending invalid credentials to SOGo, and as long as admins are only logged into one mailbox, should work as expected.
The workaround will still stop working as soon as an admin opens multiple mailboxes, but would at least skip this check / send empty authentication headers as before.

**Review by mhofer117 — CHANGES_REQUESTED** [review]
It looks like this feature got a lot of improvents since the initial implementation, great! 👍 

Because I was mentioned I reviewed the PR and made a suggestion to improve it.

It's worth noting that the bug mentioned in #4333 will not be reliably fixed for the ALLOW_ADMIN_EMAIL_LOGIN feature.
Maybe this limitation should be added to the docs or at least mentioned in a code comment, now that it's known.

File: data/web/sogo-auth.php (hunk 1 above)
Comment (mkuron) [reply data/web/sogo-auth.php]: I thought about the admin login too, but since even your suggestion only fixes the problem as long as only a single mailbox is opened, I don‘t think it’s worth bothering with. I’ll add a note to https://github.com/mailcow/mailcow-dockerized-docs/blob/Master/docs/debug-admin_login_sogo.md. Instead. Also note that I found that `$_ SESSION[$session_var_user_allowed]` sometimes contains the same email address multiple times, so it would need to be deduplicated before doing as you suggest.

**Comment by DerLinkman** [comment]
So, guys? What are the results (in short) of your tests? Does it work? I don´t know actually what has changed :)

**Comment by dragoangel** [comment]
Tested,

- from user perspective sogo-auth works fine after fix and I tested that user can't open another user resources by changing url, all fine.
- from admin perspective it return 403 forbidden always on subscribe requests, previously it return 302 and reload the page (same as before fix for user used sogo-auth). Admin user still can open multiply users on separate tabs, or by changing email in url.

Honestly not understand the logic fully, but why admin when he can do request  any resource, for another user as well got forbidden?

File: data/web/sogo-auth.php (hunk 1 above)
Comment (dragoangel) [reply data/web/sogo-auth.php]: Also need rephrase text in `debug-admin_login_sogo` doc:
`All of these options / behaviors are disabled if the ALLOW_ADMIN_EMAIL_LOGIN is not enabled in the config.`
`Drawbacks when enabled`
because now any user have `login to web` button which works in mostly same way.

Comment (jkellerer) [reply data/web/sogo-auth.php]: In general the change looks ok (besides the concern below). What `sogo-auth.php` does is telling Sogo what user/mailbox to use when calling its REST endpoints. In addition we also provide the mailbox password that Sogo uses to login to dovecot (both items are provided as X-headers).

I do have one concern with the change: The code in GET login checks if `$login` has access and adds it to the list only then. Using `$_SESSION['mailcow_cc_username']` directly without checks might be dangerous. How about:
```php
  // extract email address from "/SOGo/so/user@domain/xy"
  $url_parts = explode("/", $_SERVER['HTTP_X_ORIGINAL_URI']);
  $email_list = [
    $url_parts[3],                           // Requested mailbox
    ($_SESSION['mailcow_cc_username'] ?? '') // Current user
  ];

  foreach ($email_list as $email) {
    // check if this email is in session allowed list
    if (
        !empty($email) &&
        filter_var($email, FILTER_VALIDATE_EMAIL) &&
        is_array($_SESSION[$session_var_user_allowed]) &&
        in_array($email, $_SESSION[$session_var_user_allowed])
    ) {
      $username = $email;
      $password = $_SESSION[$session_var_pass];
      header("X-User: $username");
      header("X-Auth: Basic ".base64_encode("$username:$password"));
      header("X-Auth-Type: Basic");
      exit;
    }
  }
```
This still prefers the requested mailbox and falls back to the current user (when it is a "user" account where login is email address and only when `$_SESSION[$session_var_user_allowed]` contains it). All existing checks remain in place since the condition only succeeds if the current user session has access.

Comment (mkuron) [reply data/web/sogo-auth.php]: Thanks for taking a look, @jkellerer. `$_SESSION['mailcow_cc_username']` is always present in `$_SESSION[$session_var_user_allowed]`, so I don't understand how your code would change anything. I don't think `$_SESSION['mailcow_cc_username']` might be dangerous -- it's a session variable, so we can trust that it always contains the name of the logged-in user and cannot be overwritten by the client.

**Comment by mkuron** [comment]
> Honestly not understand the logic fully, but why admin when he can do request any resource, for another user as well got forbidden?

The trouble is that we can't tell which user a request needs to be performed as. The URL for the requests in my initial comments contains a different user name than the user we are logged in as. It does work when the admin is logged in with both users simultaneously.

**Comment by dragoangel** [comment]
> It does work when the admin is logged in with both users simultaneously.

Yep, it works. If this would be mentioned in docs it enouth really I thing.

File: data/web/sogo-auth.php (hunk 1 above)
Comment (jkellerer) [reply data/web/sogo-auth.php]: Hi @mkuron, yes I agree to your statement, however your change adds a separate logic branch by always accepting `$_SESSION['mailcow_cc_username']` for SSO without requiring to go through `if (isset($_GET['login'])) { ... }` (the explicit request to SSO to SOGo). The only reason why SSO to SOGo still requires the `$_GET['login']` logic for an ordinary user is that `$_SESSION[$session_var_pass]` is unset at first but this is a side effect. 

For that reason I think it would be cleaner to keep it separated: 
* The first logic branch (`$_GET['login']` logic) fills the array of allowed mail accounts for SSO for the current user
* The second logic branch handles auth requests for SOGo on a list of possible mail-accounts for a request. Either the ones explicitly requested in the URL, or the user's own (possibly including the latest dual login). 
* Only the first branch needs to deal with "is it allowed" the second only needs to interpret which mailbox is requested (concerns are separated).

E.g. by extending `$email_list` you can even support the latest dual login of the admin:
```php
  $email_list = [
    $url_parts[3],                               // Requested mailbox
    ($_SESSION['mailcow_cc_username'] ?? ''),    // Current user
    ($_SESSION["dual-login"]["username"] ?? ''), // Dual login user
  ];
```

Comment (mkuron) [reply data/web/sogo-auth.php]: @jkellerer, thanks for the explanation. Your solution is indeed better and I have updated my pull request.

**Comment by mkuron** [comment]
@DerLinkman, this is ready to be merged and you can go ahead and put it into the 2022-01a release.

**Comment by DerLinkman** [comment]
> @DerLinkman, this is ready to be merged and you can go ahead and put it into the 2022-01a release.

Awesome 👍 I'll merge it tomorrow or Tuesday and will release the Bugfix Update then, combined with the other 2-4 fixes/additions.
